# Generated by Django 5.1.5 on 2025-02-04 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quit_date', models.DateField(default=django.utils.timezone.now)),
                ('cigs_per_day', models.PositiveIntegerField(default=20)),
                ('cost_per_pack', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cigs_in_pack', models.PositiveIntegerField(default=20)),
                ('baseline_co_level', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
