# Generated by Django 5.1.5 on 2025-02-04 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardstats',
            name='quit_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Temporary change'),
        ),
    ]
