# Generated by Django 5.1.5 on 2025-02-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardstats',
            name='cigarettes_avoided',
        ),
        migrations.RemoveField(
            model_name='dashboardstats',
            name='co_level',
        ),
        migrations.RemoveField(
            model_name='dashboardstats',
            name='money_saved',
        ),
        migrations.AddField(
            model_name='dashboardstats',
            name='baseline_co_level',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='dashboardstats',
            name='cigs_in_pack',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='dashboardstats',
            name='cigs_per_day',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='dashboardstats',
            name='cost_per_pack',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
