# Generated by Django 5.1.5 on 2025-02-04 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_dashboardstats_cigarettes_avoided_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardstats',
            name='quit_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 14, 21, 13, 581901, tzinfo=datetime.timezone.utc)),
        ),
    ]
