# Generated by Django 5.1.5 on 2025-02-04 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboardstats_quit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardstats',
            name='quit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
